---
- hosts: undercloud
  vars:
    metadata:
      name: Validate the Heat environment file for network configuration
      description: >
        This validates the network environment and nic-config files
        that specify the overcloud network configuration.

        The deployers are expected to write these files themselves as
        described in the Network Isolation guide:

        http://tripleo.org/advanced_deployment/network_isolation.html
      groups:
      - discovery
    network_environment_path: /home/stack/network-environment.yaml
  tasks:
  - name: Validate the network environment files
    validate_network_environment:
      path: "{{ network_environment_path }}"
